// Code generated by goctl. DO NOT EDIT!
// Source: relation.proto

package server

import (
	"context"

	"github.com/cherish-chat/xxim-server/app/relation/internal/logic"
	"github.com/cherish-chat/xxim-server/app/relation/internal/svc"
	"github.com/cherish-chat/xxim-server/common/pb"
)

type RelationServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRelationServiceServer
}

func NewRelationServiceServer(svcCtx *svc.ServiceContext) *RelationServiceServer {
	return &RelationServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationServiceServer) AreFriends(ctx context.Context, in *pb.AreFriendsReq) (*pb.AreFriendsResp, error) {
	l := logic.NewAreFriendsLogic(ctx, s.svcCtx)
	return l.AreFriends(in)
}

func (s *RelationServiceServer) AreBlackList(ctx context.Context, in *pb.AreBlackListReq) (*pb.AreBlackListResp, error) {
	l := logic.NewAreBlackListLogic(ctx, s.svcCtx)
	return l.AreBlackList(in)
}

func (s *RelationServiceServer) RequestAddFriend(ctx context.Context, in *pb.RequestAddFriendReq) (*pb.RequestAddFriendResp, error) {
	l := logic.NewRequestAddFriendLogic(ctx, s.svcCtx)
	return l.RequestAddFriend(in)
}

func (s *RelationServiceServer) AcceptAddFriend(ctx context.Context, in *pb.AcceptAddFriendReq) (*pb.AcceptAddFriendResp, error) {
	l := logic.NewAcceptAddFriendLogic(ctx, s.svcCtx)
	return l.AcceptAddFriend(in)
}

func (s *RelationServiceServer) RejectAddFriend(ctx context.Context, in *pb.RejectAddFriendReq) (*pb.RejectAddFriendResp, error) {
	l := logic.NewRejectAddFriendLogic(ctx, s.svcCtx)
	return l.RejectAddFriend(in)
}

func (s *RelationServiceServer) GetFriendCount(ctx context.Context, in *pb.GetFriendCountReq) (*pb.GetFriendCountResp, error) {
	l := logic.NewGetFriendCountLogic(ctx, s.svcCtx)
	return l.GetFriendCount(in)
}

func (s *RelationServiceServer) BlockUser(ctx context.Context, in *pb.BlockUserReq) (*pb.BlockUserResp, error) {
	l := logic.NewBlockUserLogic(ctx, s.svcCtx)
	return l.BlockUser(in)
}

func (s *RelationServiceServer) DeleteBlockUser(ctx context.Context, in *pb.DeleteBlockUserReq) (*pb.DeleteBlockUserResp, error) {
	l := logic.NewDeleteBlockUserLogic(ctx, s.svcCtx)
	return l.DeleteBlockUser(in)
}

func (s *RelationServiceServer) DeleteFriend(ctx context.Context, in *pb.DeleteFriendReq) (*pb.DeleteFriendResp, error) {
	l := logic.NewDeleteFriendLogic(ctx, s.svcCtx)
	return l.DeleteFriend(in)
}

func (s *RelationServiceServer) SetSingleChatSetting(ctx context.Context, in *pb.SetSingleChatSettingReq) (*pb.SetSingleChatSettingResp, error) {
	l := logic.NewSetSingleChatSettingLogic(ctx, s.svcCtx)
	return l.SetSingleChatSetting(in)
}

func (s *RelationServiceServer) SetSingleMsgNotifyOpt(ctx context.Context, in *pb.SetSingleMsgNotifyOptReq) (*pb.SetSingleMsgNotifyOptResp, error) {
	l := logic.NewSetSingleMsgNotifyOptLogic(ctx, s.svcCtx)
	return l.SetSingleMsgNotifyOpt(in)
}

func (s *RelationServiceServer) GetSingleChatSetting(ctx context.Context, in *pb.GetSingleChatSettingReq) (*pb.GetSingleChatSettingResp, error) {
	l := logic.NewGetSingleChatSettingLogic(ctx, s.svcCtx)
	return l.GetSingleChatSetting(in)
}

func (s *RelationServiceServer) GetSingleMsgNotifyOpt(ctx context.Context, in *pb.GetSingleMsgNotifyOptReq) (*pb.GetSingleMsgNotifyOptResp, error) {
	l := logic.NewGetSingleMsgNotifyOptLogic(ctx, s.svcCtx)
	return l.GetSingleMsgNotifyOpt(in)
}

func (s *RelationServiceServer) GetFriendList(ctx context.Context, in *pb.GetFriendListReq) (*pb.GetFriendListResp, error) {
	l := logic.NewGetFriendListLogic(ctx, s.svcCtx)
	return l.GetFriendList(in)
}
