// Code generated by goctl. DO NOT EDIT.
// Source: gateway.peer.proto

package server

import (
	"context"

	"github.com/cherish-chat/xxim-proto/peerpb"
	"github.com/cherish-chat/xxim-server/app/api/gateway/internal/logic/internalservice"
	"github.com/cherish-chat/xxim-server/app/api/gateway/internal/svc"
)

type InternalServiceServer struct {
	svcCtx *svc.ServiceContext
	peerpb.UnimplementedInternalServiceServer
}

func NewInternalServiceServer(svcCtx *svc.ServiceContext) *InternalServiceServer {
	return &InternalServiceServer{
		svcCtx: svcCtx,
	}
}

// GatewayWriteData 向用户推送数据
func (s *InternalServiceServer) GatewayWriteData(ctx context.Context, in *peerpb.GatewayWriteDataReq) (*peerpb.GatewayWriteDataResp, error) {
	l := internalservicelogic.NewGatewayWriteDataLogic(ctx, s.svcCtx)
	return l.GatewayWriteData(in)
}
