// Code generated by goctl. DO NOT EDIT.
// Source: gateway.peer.proto

package server

import (
	"context"

	"github.com/cherish-chat/xxim-proto/peerpb"
	"github.com/cherish-chat/xxim-server/app/api/gateway/internal/logic/internalservice"
	"github.com/cherish-chat/xxim-server/app/api/gateway/internal/svc"
)

type InternalServiceServer struct {
	svcCtx *svc.ServiceContext
	peerpb.UnimplementedInternalServiceServer
}

func NewInternalServiceServer(svcCtx *svc.ServiceContext) *InternalServiceServer {
	return &InternalServiceServer{
		svcCtx: svcCtx,
	}
}

// ListLongConnection 获取长连接列表
func (s *InternalServiceServer) ListLongConnection(ctx context.Context, in *peerpb.ListLongConnectionReq) (*peerpb.ListLongConnectionResp, error) {
	l := internalservicelogic.NewListLongConnectionLogic(ctx, s.svcCtx)
	return l.ListLongConnection(in)
}
