// Code generated by goctl. DO NOT EDIT.
// Source: third.proto

package server

import (
	"context"

	"github.com/cherish-chat/xxim-server/app/third/internal/logic/smsservice"
	"github.com/cherish-chat/xxim-server/app/third/internal/svc"
	"github.com/cherish-chat/xxim-server/common/pb"
)

type SmsServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSmsServiceServer
}

func NewSmsServiceServer(svcCtx *svc.ServiceContext) *SmsServiceServer {
	return &SmsServiceServer{
		svcCtx: svcCtx,
	}
}

// SmsCodeSend 发送短信
func (s *SmsServiceServer) SmsCodeSend(ctx context.Context, in *pb.SmsCodeSendReq) (*pb.SmsCodeSendResp, error) {
	l := smsservicelogic.NewSmsCodeSendLogic(ctx, s.svcCtx)
	return l.SmsCodeSend(in)
}

// SmsCodeVerify 验证短信
func (s *SmsServiceServer) SmsCodeVerify(ctx context.Context, in *pb.SmsCodeVerifyReq) (*pb.SmsCodeVerifyResp, error) {
	l := smsservicelogic.NewSmsCodeVerifyLogic(ctx, s.svcCtx)
	return l.SmsCodeVerify(in)
}
