// Code generated by goctl. DO NOT EDIT.
// Source: third.peer.proto

package server

import (
	"context"

	"github.com/cherish-chat/xxim-proto/peerpb"
	"github.com/cherish-chat/xxim-server/app/service/third/internal/logic/emailservice"
	"github.com/cherish-chat/xxim-server/app/service/third/internal/svc"
)

type EmailServiceServer struct {
	svcCtx *svc.ServiceContext
	peerpb.UnimplementedEmailServiceServer
}

func NewEmailServiceServer(svcCtx *svc.ServiceContext) *EmailServiceServer {
	return &EmailServiceServer{
		svcCtx: svcCtx,
	}
}

// EmailCodeSend 发送邮件
func (s *EmailServiceServer) EmailCodeSend(ctx context.Context, in *peerpb.EmailCodeSendReq) (*peerpb.EmailCodeSendResp, error) {
	l := emailservicelogic.NewEmailCodeSendLogic(ctx, s.svcCtx)
	return l.EmailCodeSend(in)
}

// EmailCodeVerify 验证邮件
func (s *EmailServiceServer) EmailCodeVerify(ctx context.Context, in *peerpb.EmailCodeVerifyReq) (*peerpb.EmailCodeVerifyResp, error) {
	l := emailservicelogic.NewEmailCodeVerifyLogic(ctx, s.svcCtx)
	return l.EmailCodeVerify(in)
}
