// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: dispatch.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DispatchServiceClient is the client API for DispatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DispatchServiceClient interface {
	//DispatchOnlineCallback 上线回调
	//二次开发人员可以在此接口中实现上线回调逻辑
	DispatchOnlineCallback(ctx context.Context, in *DispatchOnlineCallbackReq, opts ...grpc.CallOption) (*DispatchOnlineCallbackResp, error)
	//DispatchOfflineCallback 下线回调
	//二次开发人员可以在此接口中实现下线回调逻辑
	DispatchOfflineCallback(ctx context.Context, in *DispatchOfflineCallbackReq, opts ...grpc.CallOption) (*DispatchOfflineCallbackResp, error)
	//BeforeConnect 服务端连接前的回调
	//二次开发人员可以在此接口中实现服务端连接前的逻辑，比如校验token
	BeforeConnect(ctx context.Context, in *BeforeConnectReq, opts ...grpc.CallOption) (*BeforeConnectResp, error)
}

type dispatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchServiceClient(cc grpc.ClientConnInterface) DispatchServiceClient {
	return &dispatchServiceClient{cc}
}

func (c *dispatchServiceClient) DispatchOnlineCallback(ctx context.Context, in *DispatchOnlineCallbackReq, opts ...grpc.CallOption) (*DispatchOnlineCallbackResp, error) {
	out := new(DispatchOnlineCallbackResp)
	err := c.cc.Invoke(ctx, "/pb.dispatchService/DispatchOnlineCallback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) DispatchOfflineCallback(ctx context.Context, in *DispatchOfflineCallbackReq, opts ...grpc.CallOption) (*DispatchOfflineCallbackResp, error) {
	out := new(DispatchOfflineCallbackResp)
	err := c.cc.Invoke(ctx, "/pb.dispatchService/DispatchOfflineCallback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) BeforeConnect(ctx context.Context, in *BeforeConnectReq, opts ...grpc.CallOption) (*BeforeConnectResp, error) {
	out := new(BeforeConnectResp)
	err := c.cc.Invoke(ctx, "/pb.dispatchService/BeforeConnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatchServiceServer is the server API for DispatchService service.
// All implementations must embed UnimplementedDispatchServiceServer
// for forward compatibility
type DispatchServiceServer interface {
	//DispatchOnlineCallback 上线回调
	//二次开发人员可以在此接口中实现上线回调逻辑
	DispatchOnlineCallback(context.Context, *DispatchOnlineCallbackReq) (*DispatchOnlineCallbackResp, error)
	//DispatchOfflineCallback 下线回调
	//二次开发人员可以在此接口中实现下线回调逻辑
	DispatchOfflineCallback(context.Context, *DispatchOfflineCallbackReq) (*DispatchOfflineCallbackResp, error)
	//BeforeConnect 服务端连接前的回调
	//二次开发人员可以在此接口中实现服务端连接前的逻辑，比如校验token
	BeforeConnect(context.Context, *BeforeConnectReq) (*BeforeConnectResp, error)
	mustEmbedUnimplementedDispatchServiceServer()
}

// UnimplementedDispatchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDispatchServiceServer struct {
}

func (UnimplementedDispatchServiceServer) DispatchOnlineCallback(context.Context, *DispatchOnlineCallbackReq) (*DispatchOnlineCallbackResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DispatchOnlineCallback not implemented")
}
func (UnimplementedDispatchServiceServer) DispatchOfflineCallback(context.Context, *DispatchOfflineCallbackReq) (*DispatchOfflineCallbackResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DispatchOfflineCallback not implemented")
}
func (UnimplementedDispatchServiceServer) BeforeConnect(context.Context, *BeforeConnectReq) (*BeforeConnectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeforeConnect not implemented")
}
func (UnimplementedDispatchServiceServer) mustEmbedUnimplementedDispatchServiceServer() {}

// UnsafeDispatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatchServiceServer will
// result in compilation errors.
type UnsafeDispatchServiceServer interface {
	mustEmbedUnimplementedDispatchServiceServer()
}

func RegisterDispatchServiceServer(s grpc.ServiceRegistrar, srv DispatchServiceServer) {
	s.RegisterService(&DispatchService_ServiceDesc, srv)
}

func _DispatchService_DispatchOnlineCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchOnlineCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).DispatchOnlineCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.dispatchService/DispatchOnlineCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).DispatchOnlineCallback(ctx, req.(*DispatchOnlineCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_DispatchOfflineCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchOfflineCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).DispatchOfflineCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.dispatchService/DispatchOfflineCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).DispatchOfflineCallback(ctx, req.(*DispatchOfflineCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_BeforeConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeforeConnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).BeforeConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.dispatchService/BeforeConnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).BeforeConnect(ctx, req.(*BeforeConnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DispatchService_ServiceDesc is the grpc.ServiceDesc for DispatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DispatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.dispatchService",
	HandlerType: (*DispatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchOnlineCallback",
			Handler:    _DispatchService_DispatchOnlineCallback_Handler,
		},
		{
			MethodName: "DispatchOfflineCallback",
			Handler:    _DispatchService_DispatchOfflineCallback_Handler,
		},
		{
			MethodName: "BeforeConnect",
			Handler:    _DispatchService_BeforeConnect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dispatch.proto",
}
