// Code generated by goctl. DO NOT EDIT.
// Source: message.peer.proto

package noticeservice

import (
	"context"

	"github.com/cherish-chat/xxim-proto/peerpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	MessageContentText            = peerpb.MessageContentText
	MessageContentText_Item       = peerpb.MessageContentText_Item
	MessageContentText_Item_At    = peerpb.MessageContentText_Item_At
	MessageContentText_Item_Image = peerpb.MessageContentText_Item_Image
	MessageInsertReq              = peerpb.MessageInsertReq
	MessageInsertResp             = peerpb.MessageInsertResp
	MessagePushReq                = peerpb.MessagePushReq
	MessagePushResp               = peerpb.MessagePushResp
	MessageSendReq                = peerpb.MessageSendReq
	MessageSendResp               = peerpb.MessageSendResp
	NoticeContentJoinNewGroup     = peerpb.NoticeContentJoinNewGroup
	NoticeContentNewFriendRequest = peerpb.NoticeContentNewFriendRequest
	NoticeContentOnlineStatus     = peerpb.NoticeContentOnlineStatus
	NoticeSendReq                 = peerpb.NoticeSendReq
	NoticeSendResp                = peerpb.NoticeSendResp

	NoticeService interface {
		// NoticeSend 通知发送
		NoticeSend(ctx context.Context, in *NoticeSendReq, opts ...grpc.CallOption) (*NoticeSendResp, error)
	}

	defaultNoticeService struct {
		cli zrpc.Client
	}
)

func NewNoticeService(cli zrpc.Client) NoticeService {
	return &defaultNoticeService{
		cli: cli,
	}
}

// NoticeSend 通知发送
func (m *defaultNoticeService) NoticeSend(ctx context.Context, in *NoticeSendReq, opts ...grpc.CallOption) (*NoticeSendResp, error) {
	client := peerpb.NewNoticeServiceClient(m.cli.Conn())
	return client.NoticeSend(ctx, in, opts...)
}
