// Code generated by goctl. DO NOT EDIT.
// Source: gateway.peer.proto

package server

import (
	"context"

	"github.com/cherish-chat/xxim-proto/peerpb"
	"github.com/cherish-chat/xxim-server/app/api/gateway/internal/logic/connectionservice"
	"github.com/cherish-chat/xxim-server/app/api/gateway/internal/svc"
)

type ConnectionServiceServer struct {
	svcCtx *svc.ServiceContext
	peerpb.UnimplementedConnectionServiceServer
}

func NewConnectionServiceServer(svcCtx *svc.ServiceContext) *ConnectionServiceServer {
	return &ConnectionServiceServer{
		svcCtx: svcCtx,
	}
}

// WriteData 向用户推送数据
func (s *ConnectionServiceServer) WriteData(ctx context.Context, in *peerpb.GatewayWriteDataContent) (*peerpb.GatewayWriteDataContent, error) {
	l := connectionservicelogic.NewWriteDataLogic(ctx, s.svcCtx)
	return l.WriteData(in)
}
