// Code generated by goctl. DO NOT EDIT.
// Source: gateway.peer.proto

package server

import (
	"context"

	"github.com/cherish-chat/xxim-proto/peerpb"
	"github.com/cherish-chat/xxim-server/app/api/gateway/internal/logic/connectionservice"
	"github.com/cherish-chat/xxim-server/app/api/gateway/internal/svc"
)

type ConnectionServiceServer struct {
	svcCtx *svc.ServiceContext
	peerpb.UnimplementedConnectionServiceServer
}

func NewConnectionServiceServer(svcCtx *svc.ServiceContext) *ConnectionServiceServer {
	return &ConnectionServiceServer{
		svcCtx: svcCtx,
	}
}

// ListLongConnection 获取长连接列表
func (s *ConnectionServiceServer) ListLongConnection(ctx context.Context, in *peerpb.ListLongConnectionReq) (*peerpb.ListLongConnectionResp, error) {
	l := connectionservicelogic.NewListLongConnectionLogic(ctx, s.svcCtx)
	return l.ListLongConnection(in)
}

// GatewayKickLongConnection 踢掉连接
func (s *ConnectionServiceServer) GatewayKickLongConnection(ctx context.Context, in *peerpb.GatewayKickLongConnectionReq) (*peerpb.GatewayKickLongConnectionResp, error) {
	l := connectionservicelogic.NewGatewayKickLongConnectionLogic(ctx, s.svcCtx)
	return l.GatewayKickLongConnection(in)
}
