// Code generated by goctl. DO NOT EDIT.
// Source: third.peer.proto

package smsservice

import (
	"context"

	"github.com/cherish-chat/xxim-proto/peerpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CaptchaVerifyReq    = peerpb.CaptchaVerifyReq
	CaptchaVerifyResp   = peerpb.CaptchaVerifyResp
	EmailCodeSendReq    = peerpb.EmailCodeSendReq
	EmailCodeSendResp   = peerpb.EmailCodeSendResp
	EmailCodeVerifyReq  = peerpb.EmailCodeVerifyReq
	EmailCodeVerifyResp = peerpb.EmailCodeVerifyResp
	GetCaptchaReq       = peerpb.GetCaptchaReq
	GetCaptchaResp      = peerpb.GetCaptchaResp
	SmsCodeSendReq      = peerpb.SmsCodeSendReq
	SmsCodeSendResp     = peerpb.SmsCodeSendResp
	SmsCodeVerifyReq    = peerpb.SmsCodeVerifyReq
	SmsCodeVerifyResp   = peerpb.SmsCodeVerifyResp

	SmsService interface {
		// SmsCodeSend 发送短信
		SmsCodeSend(ctx context.Context, in *SmsCodeSendReq, opts ...grpc.CallOption) (*SmsCodeSendResp, error)
		// SmsCodeVerify 验证短信
		SmsCodeVerify(ctx context.Context, in *SmsCodeVerifyReq, opts ...grpc.CallOption) (*SmsCodeVerifyResp, error)
	}

	defaultSmsService struct {
		cli zrpc.Client
	}
)

func NewSmsService(cli zrpc.Client) SmsService {
	return &defaultSmsService{
		cli: cli,
	}
}

// SmsCodeSend 发送短信
func (m *defaultSmsService) SmsCodeSend(ctx context.Context, in *SmsCodeSendReq, opts ...grpc.CallOption) (*SmsCodeSendResp, error) {
	client := peerpb.NewSmsServiceClient(m.cli.Conn())
	return client.SmsCodeSend(ctx, in, opts...)
}

// SmsCodeVerify 验证短信
func (m *defaultSmsService) SmsCodeVerify(ctx context.Context, in *SmsCodeVerifyReq, opts ...grpc.CallOption) (*SmsCodeVerifyResp, error) {
	client := peerpb.NewSmsServiceClient(m.cli.Conn())
	return client.SmsCodeVerify(ctx, in, opts...)
}
