// Code generated by goctl. DO NOT EDIT.
// Source: message.peer.proto

package server

import (
	"context"

	"github.com/cherish-chat/xxim-proto/peerpb"
	"github.com/cherish-chat/xxim-server/app/service/message/internal/logic/messageservice"
	"github.com/cherish-chat/xxim-server/app/service/message/internal/svc"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	peerpb.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

// MessageInsert 插入消息
func (s *MessageServiceServer) MessageInsert(ctx context.Context, in *peerpb.MessageInsertReq) (*peerpb.MessageInsertResp, error) {
	l := messageservicelogic.NewMessageInsertLogic(ctx, s.svcCtx)
	return l.MessageInsert(in)
}

// MessageSend 发送消息
func (s *MessageServiceServer) MessageSend(ctx context.Context, in *peerpb.MessageSendReq) (*peerpb.MessageSendResp, error) {
	l := messageservicelogic.NewMessageSendLogic(ctx, s.svcCtx)
	return l.MessageSend(in)
}

// MessagePush 推送消息
func (s *MessageServiceServer) MessagePush(ctx context.Context, in *peerpb.MessagePushReq) (*peerpb.MessagePushResp, error) {
	l := messageservicelogic.NewMessagePushLogic(ctx, s.svcCtx)
	return l.MessagePush(in)
}
